### PR TITLE
Fixed specs with name formatting

### PR DESCRIPTION
**Pull request by TheLucasMoore**
This resolves issue #4.

### CODE REVIEW

**Comment by TheLucasMoore** [comment]
@PeterBell

**Comment by PeterBell** [comment]
Hey @aturkewi or @mendelB mind having a quick look and checking this out?

**Comment by aturkewi** [comment]
Just checked this against the solution branch and it looks like this all still works. I've definitely seen people have trouble with this formatting, so thanks for the fix @TheLucasMoore !

One thing before I merge this PR though. Can you make and identical PR to the solution branch? We always want to keep the solution branch and the master branch in sync. The best way to do this is to `git log` on the master branch and copy the 7 digits associated to the commit(s) you want to copy to the solution branch. Then, check out the solution branch, and use `git cherry-pick <commit-to-copy-over>`. Push that up and make a PR as well.

Thank I'll be able to merge them both in.

Thanks again!

**Comment by AnnJohn** [comment]
@TheLucasMoore could you update based on @aturkewi's comments? thanks!

**Pull request merged**
